fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "w")
write(fh, "step1: lua running\n")
closefile(fh)
open("D:\\FEMM Source\\femmTestFiles\\pourleroi_cc_magnetostatic_rev2.fem")
fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "a")
write(fh, "step2: file opened\n")
closefile(fh)
mi_saveas("D:\\FEMM Source\\femmTestFiles\\_rev2_test.fem")
fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "a")
write(fh, "step3: saved\n")
closefile(fh)
mi_setmatperplenz("Amorphous gap", 0)
fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "a")
write(fh, "step4: setmatperplenz returned\n")
closefile(fh)
mi_saveas("D:\\FEMM Source\\femmTestFiles\\_rev2_test.fem")
fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "a")
write(fh, "step5: saved again\n")
closefile(fh)
mi_analyze(1)
fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "a")
write(fh, "step6: analyze done\n")
closefile(fh)
mi_loadsolution()
fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "a")
write(fh, "step7: solution loaded\n")
closefile(fh)
ci, vi, fi = mo_getcircuitproperties("coil")
fh = openfile("D:\\FEMM Source\\femmTestFiles\\_sanity.txt", "a")
write(fh, format("step8: |I|=%.3e A  |V|=%.3e V  |flx|=%.3e Wb\n", abs(ci), abs(vi), abs(fi)))
closefile(fh)
mo_close()
mi_close()
